// Auto-generated by safeword from SAFEWORD_SCHEMA. Do not edit by hand.
// Source: ownedFiles ∪ managedFiles ∪ jsonMerges ∪ textPatches → top-level prefixes.
// Regenerated on every `safeword install`.

export const SAFEWORD_PATHS: readonly string[] = [
  '.claude/',
  '.cursor/',
  '.dprint.json',
  '.dprint.jsonc',
  '.gitattributes',
  '.github/',
  '.gitignore',
  '.golangci.yml',
  '.husky/',
  '.importlinter',
  '.jscpd.json',
  '.markdownlint-cli2.jsonc',
  '.mcp.json',
  '.oxfmtrc.json',
  '.oxfmtrc.jsonc',
  '.prettierignore',
  '.prettierrc',
  '.safeword-project/',
  '.project/',
  '.safeword/',
  '.sqlfluff',
  'biome.json',
  'biome.jsonc',
  'clippy.toml',
  'cucumber.mjs',
  'deny.toml',
  'dprint.json',
  'dprint.jsonc',
  'eslint.config.mjs',
  'features/',
  'knip.json',
  'mypy.ini',
  'package.json',
  'ruff.toml',
  'rustfmt.toml',
  'steps/',
  'tsconfig.json',
];

/**
 * Match a file path against the safeword-managed set. Directory prefixes
 * (entries ending in `/`) match by `startsWith`; bare file paths must
 * match exactly so e.g. `package.json.bak` does not match `package.json`.
 */
export function isSafewordPath(file: string): boolean {
  for (const prefix of SAFEWORD_PATHS) {
    if (prefix.endsWith('/')) {
      if (file.startsWith(prefix)) return true;
    } else if (file === prefix) {
      return true;
    }
  }
  return false;
}

/**
 * Pick the safeword-managed subset of files reported by `git diff --name-only`
 * (changed) and `git ls-files --others --exclude-standard` (untracked).
 * Used by the auto-upgrade hook to decide what to stage after `safeword install`.
 */
export function filterSafewordFiles(
  changedFiles: readonly string[],
  untrackedFiles: readonly string[],
): readonly string[] {
  return [...changedFiles, ...untrackedFiles].filter(f => isSafewordPath(f));
}
